### ISSUE TITLE
Variable font: odd difference between hb-shape and uharfbuzz

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#43]
I'm observing a difference of one unit for an advance width in a variable font between hb-shape and uharfbuzz: at one location the unrounded advance would be exactly 495.5: with hb-shape this gets rounded up to 496 (which is correct) and with uharfbuzz it gets rounded down to 495 (which isn't).

I have constructed the font so that the normalized axis value is perfectly representable as a 2dot14 fixed.

The attached zip file contains a test font and a test script. The font contains one glyph ("A") and one axis ("TEST").

The TEST axis goes from 482 to 518, with the default right in the middle at 500.
The advance width of glyph A goes from 491 to 509, with the default at 500. So the axis value moves twice as fast as the advance width.

At TEST=491 (in between min and default) the problem occurs.

The output of the test script:
```
482 - 491 491 491.0 True
491 - 495 496 495.5 False
500 - 500 500 500.0 True
509 - 505 505 504.5 True
518 - 509 509 509.0 True
```
(Axis value, uharfbuzz advance, hb-shape advance, unrounded advance, equal)

The hb-shape version I tested with was 2.6.2, uharfbuzz is at HB 2.6.5.

[round_test.zip](https://github.com/harfbuzz/uharfbuzz/files/4671226/round_test.zip)

**Comment by justvanrossum** [comment]
Note that at TEST=509 the values _do_ match, which makes me think perhaps a negative delta gets rounded differently between the two environments.

**Comment by behdad** [comment]
Please try with `--font-funcs` set to `ot` vs `ft`.  I feel like that's where the difference is coming from.

**Comment by justvanrossum** [comment]
Ha, calling hb-shape with `--font-funcs=ot` indeed makes a difference. The output then becomes:
```
482 - 491 491 491.0 True
491 - 495 495 495.5 True
500 - 500 500 500.0 True
509 - 505 504 504.5 False
518 - 509 509 509.0 True
```
Which is weird, because that _also_ doesn't match the output of uharfbuzz, but differently.

**Comment by behdad** [comment]
I have to dig in, but I wonder if Python is changing FPU rounding mode..

**Comment by ebraminio** [comment]
Will look at this also

**Comment by ebraminio** [comment]
am investigating this also

**Comment by ebraminio** [comment]
Okay, this is fixed with https://github.com/harfbuzz/uharfbuzz/commit/985eda07c7e7d9083b5403e2b67fbd1691fba7e8 I'll add it as a test also

**Comment by anthrotype** [comment]
What fixed it?

**Comment by justvanrossum** [comment]
I'm still seeing the same results in my local build (macOS 10.15)

**Comment by ebraminio** [comment]
> What fixed it?

Good question! Maybe somewhere in skbuild / cmake process another roundf implementation / libm was inserted. 

> I'm still seeing the same results in my local build (macOS 10.15)

Are you passing `--font-funcs=ot`?

**Comment by ebraminio** [comment]
Of course I should investigate whether I had the issue before before, sorry for closing eagerly, at least I can say I don't have the difference on my machine and that's regardless of passing HAVE_ROUNDF to harfbuzz.cc compile or not.

**Comment by justvanrossum** [comment]
I updated my hb-shape executable, and the results now indeed match when using `--font-funcs=ot`, so my original report (based on HB 2.6.2) was out of date. So there's indeed no issue with uharfbuzz.

That said, I'd argue that the values returned with `--font-funcs=ot` are incorrectly rounded, and should match the results of `--font-funcs=ft`, but that would be a HB issue.

**Comment by ebraminio** [comment]
Thank you!

> That said, I'd argue that the values returned with --font-funcs=ot are incorrectly rounded, and should match the results of --font-funcs=ft, but that would be a HB issue.

Feel free to file that as a bug against harfbuzz.
